services:
  - type: web
    name: token-scanner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SCANNER_WALLET
        value: "0x8C0083EE1a611c917E3652a14f9Ab5c3a23948D3"
    plan: free
